### ISSUE TITLE
Adding % / another string at the end of the pie text

### ISSUE THREAD

**Issue by theunreal** [oliviale/CSS-Progress-Pie#1]
Is it possible to modify the pie text and adding "%" as suffix? I tried to change the SASS but it turns out that it is not that simple

**Comment by oliviale** [comment]
Hey, it is possible but there isn't much space for a long string. '%' is fine though.
In the `.progress-pie:after`, the `content: attr(data-value)`  can be `content: "word" attr(data-value) "%"` 

You'll have to tweak the font-size and padding so that the text fits nicely in the circle. This is how it looks like:

![image](https://user-images.githubusercontent.com/9974754/68349510-5ab79b00-0138-11ea-986c-529163bba56a.png)

**Comment by theunreal** [comment]
> Hey, it is possible but there isn't much space for a long string. '%' is fine though.
> In the `.progress-pie:after`, the `content: attr(data-value)` can be `content: "word" attr(data-value) "%"`
> 
> You'll have to tweak the font-size and padding so that the text fits nicely in the circle. This is how it looks like:
> 
> ![image](https://user-images.githubusercontent.com/9974754/68349510-5ab79b00-0138-11ea-986c-529163bba56a.png)

Thanks!
That's actually simple, I was trying to content: attr(data-value) + "%" and had no idea why it's all messed up.
I just want to add "%" because it's not very clear the number is percent ;)
